//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.02 at 11:39:37 AM IST 
//


package localhost._8080.studentdetails.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for uniMaster complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="uniMaster">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="college" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="student" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="stuId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "uniMaster", propOrder = {
    "college",
    "student",
    "stuId"
})
public class UniMaster {

    @XmlElement(required = true)
    protected String college;
    @XmlElement(required = true)
    protected String student;
    @XmlElement(required = true)
    protected String stuId;

    /**
     * Gets the value of the college property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCollege() {
        return college;
    }

    /**
     * Sets the value of the college property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCollege(String value) {
        this.college = value;
    }

    /**
     * Gets the value of the student property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStudent() {
        return student;
    }

    /**
     * Sets the value of the student property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStudent(String value) {
        this.student = value;
    }

    /**
     * Gets the value of the stuId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStuId() {
        return stuId;
    }

    /**
     * Sets the value of the stuId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStuId(String value) {
        this.stuId = value;
    }

}
